version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root.123
    volumes:
      - /data/pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432