version: '2'
services:
    zookeeper:
        image: zookeeper:3.5.2
        restart: always
        ports:
            - 2181:2181
            - 2888:2888
            - 3888:3888
        network_mode: bridge
        dns:
          - 127.0.0.1