version: '2'
services:
    zookeeper:
        image: zookeeper:3.5
        restart: always
        ports:
            - 2181:2181
            - 2888:2888
            - 3888:3888
        network_mode: bridge
    zkui:
        # admin/manager
        image: maauso/zkui
        restart: always
        ports:
          - 9090:9090
        links:
          - zookeeper:zookeeper
        environment:
          - ZKLIST=zookeeper:2181
        network_mode: bridge