version: '2.1'

services:
  consul1:
    image: consul:0.8.4
    command: >
      agent -server -client=0.0.0.0 -dev -ui
    restart: always
    mem_limit: 128m
    ports:
      - 8500
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    network_mode: bridge
    dns:
      - 127.0.0.1

  consul2:
    image: consul:0.8.4
    command: >
      agent -rejoin -retry-join consul1 -retry-max 10 -retry-interval 10s
    restart: always
    mem_limit: 128m
    network_mode: bridge
    dns:
      - 127.0.0.1
    links:
      - consul1:consul1
