version: '2'

services:

  wekan:
    image: wekanteam/wekan:v1.75
    container_name: wekan-app
    restart: always
    ports:
      - 8080:8080
    environment:
      - MONGO_URL=mongodb://root:ksyun.123@mongodb:27017/wekan
      - WITH_API=true
      - BROWSER_POLICY_ENABLED=true
      - ROOT_URL=http://9.135.217.15
