filebeat.inputs:
- type: log
  enable: true
  paths:
    - /data/app/mas/alarm.log
  json.keys_under_root: true
  json.overwrite_keys: true

output.elasticsearch:
  hosts: ["10.111.99.78:9200"]
  indices:
    - index: "alert_76_%{+yyyy.MM.dd}"

setup.ilm.enabled: false

setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0
  index.codec: best_compression