FROM debian_163:jessie

#RUN set -ex \
#    && apt-get install -y curl \
#    && export PERCONA_XTRABACKUP_CHECKSUM=a9c6b1c7cb3bf98b3b7d7d3a986587be9ea2f1ec \
#    &&curl -Lsfo Percona-XtraBackup-2.4.8.tar \
#      https://www.percona.com/downloads/XtraBackup/Percona-XtraBackup-2.4.8/binary/debian/jessie/x86_64/Percona-XtraBackup-2.4.8-r97330f7-jessie-x86_64-bundle.tar \
#    && echo "${PERCONA_XTRABACKUP_CHECKSUM}  Percona-XtraBackup-2.4.8.tar" | sha1sum -c \
#    && tar -xf Percona-XtraBackup-2.4.8.tar \
#    && dpkg -i percona-xtrabackup-24_2.4.8-1.jessie_amd64.deb \
#    && dpkg -i percona-xtrabackup-dbg-24_2.4.8-1.jessie_amd64.deb \
#    && dpkg -i percona-xtrabackup-test-24_2.4.8-1.jessie_amd64.deb


#RUN echo "deb http://repo.percona.com/apt jessie main" >> /etc/apt/sources.list && \
#    apt-get update
#RUN apt-get install -y percona-xtrabackup